version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile # This Dockerfile is in the root directory
    ports:
      - "8080:8080"
    networks:
      - canario-network

  templates:
    build:
      context: .
      dockerfile: ./templates/Dockerfile # This Dockerfile is in the frontend folder
    ports:
      - "80:80"
    volumes:
      - ./templates:/usr/share/nginx/html:ro # Ensure correct static file directory
      - ./templates/nginx.conf:/etc/nginx/nginx.conf:ro # Mount nginx.conf
    networks:
      - canario-network

networks:
  canario-network:
    driver: bridge
