version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile # Assuming this Dockerfile is in the root directory
    ports:
      - "8080:8080"
    networks:
      - canario-network

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile # Assuming this Dockerfile is in the frontend folder
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Mount the nginx.conf file
    networks:
      - canario-network

networks:
  canario-network:
    driver: bridge
