version: "3"
services:
  app:
    image: flask-docker-demo:latest # Use the built Docker image
    ports:
      - "5001:5000" # Expose the Flask app on port 5000
    restart: always # Ensure the container restarts if it stops
