version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    deploy:
      replicas: 3 # Scaling the service to 3 replicas for Docker Swarm
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "256M"
      restart_policy:
        condition: on-failure
