version: "3"
services:
  app:
    build: . # Use the Dockerfile in the current directory to build the image
    ports:
      - "5001:5000" # Expose the Flask app on port 5000
    restart: always # Ensure the container restarts if it stops
