version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile # This Dockerfile is in the root directory
    ports:
      - "8080:8080"
    networks:
      - canario-network

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile # This Dockerfile is in the frontend folder
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html # Mount frontend folder to Nginx's html directory
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf # Mount nginx.conf
    networks:
      - canario-network

networks:
  canario-network:
    driver: bridge
