version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile # This Dockerfile is in the root directory
    ports:
      - "8080:8080"
    networks:
      - canario-network

  templates:
    build:
      context: .
      dockerfile: ./templates/Dockerfile # This Dockerfile is in the frontend folder
    ports:
      - "80:80"
    volumes:
      - ./templates:/usr/share/nginx/html:ro # Ensure correct static file directory
      - ./templates/nginx.conf:/etc/nginx/nginx.conf:ro # Mount nginx.conf
    networks:
      - canario-network

  database:
    image: google/cloud-sdk:latest # This is an example; adjust based on your database choice
    networks:
      - canario-network
    environment:
      - DB_HOST=db # Adjust as needed based on the database service name
    expose:
      - "8081" # Assuming a custom port or using Cloud Firestore's default ports

networks:
  canario-network:
    driver: bridge
