apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 3 # Number of pods you want (3 is a basic example)
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: gcr.io/YOUR_PROJECT_ID/flask-docker-demo # Replace with your actual GCR path
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80 # Port exposed to external traffic
      targetPort: 8080 # Port on which your app listens
  type: LoadBalancer # This will create an external IP to access the app
