name: CI/CD Pipeline for Flask Appp

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: TestProjectForACIT

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Verify Installed Packages
      - name: Verify Installed Packages
        run: pip list

      # Step 5: Run Python syntax check
      - name: Check Python Syntax
        run: |
          python -m py_compile $(find . -name "*.py")

      # Step 6: Run tests
      - name: Run tests
        run: pytest test_app.py

      # Step 7: List files for debug
      - name: List files for debug
        run: ls -al

      # Step 8: Check GCP variables
      - name: Check GCP variables
        run: |
          echo "GCP_PROJECT_ID: testprojectforacit-442520 and GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: TestProjectForACIT

    env:
      GCP_PROJECT_ID: "testprojectforacit-442520" # Local variable for the GCP Project ID

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Authenticate to GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Step 3: Submit build to Google Cloud Build
      - name: Submit Build to Google Cloud Build
        run: |
          gcloud builds submit --tag gcr.io/${{ env.GCP_PROJECT_ID }}/flask-docker-demo .

      # Step 4: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy flask-app \
            --image gcr.io/${{ env.GCP_PROJECT_ID }}/flask-docker-demo \
            --region us-central1 \
            --vpc-connector flask-docker-demo \
            --platform managed \
            --allow-unauthenticated \
            --timeout 600
