name: CI/CD Pipeline for Flask App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: TestProjectForACIT

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Verify Installed Packages
      - name: Verify Installed Packages
        run: pip list

      # Step 5: Run Python syntax check
      - name: Check Python Syntax
        run: |
          python -m py_compile $(find . -name "*.py")

      - name: List files for debug
        run: ls -al

      - name: Check GCP variables
        run: |
          echo "GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }} andalso GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}"

      # Step 6: Run tests
      - name: Run tests
        run: pytest test_app.py

      # Step 8: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t flask-docker-demo .

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Authenticate with Google Cloud
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Step 3: Push Docker Image to Google Artifact Registry
      - name: Push Docker Image
        run: |
          docker tag flask-docker-demo gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-docker-demo
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-docker-demo

      # Step 4: Deploy to Google Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy flask-app \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-docker-demo \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
