name: CI/CD Pipeline for Flask App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

            # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest  # Install pytest explicitly

      # Step 4: Run Python syntax check
      - name: Check Python Syntax
        run: |
          python -m py_compile $(find . -name "*.py")

      # Step 5: Run tests (optional, if you have pytest)
      - name: Run tests
        run: |
          pytest test_app.py

      # Step 6: Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-docker-demo .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 1: Install Docker and Docker Compose
      - name: Install Docker and Docker Compose

        run: |
          sudo apt-get update
          sudo apt-get remove -y containerd containerd.io || true
          sudo apt-get install -y docker.io
          sudo apt-get install -y docker-compose

      # Step 2: Build and run Docker container locally using docker-compose
      - name: Build and run Docker container locally
        run: |
          docker-compose build  # Build the Docker images using docker-compose
          docker-compose up -d  # Run the containers in detached mode
        

      # Step 2: Authenticate with Google Cloud
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Step 3: Push Docker Image to Google Artifact Registry
      - name: Push Docker Image
        run: |
          docker tag flask-docker-demo gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-docker-demo
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-docker-demo

      # Step 4: Deploy to Google Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy flask-app \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-docker-demo \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
