name: CI/CD Pipeline for Flask App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: TestProjectForACIT

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify Installed Packages
        run: pip list

      - name: Check Python Syntax
        run: |
          python -m py_compile $(find . -name "*.py")

      - name: List files for debug
        run: ls -al

      - name: Debug: Check GCP variables
        run: |
          echo "GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}"

      - name: Run tests
        run: pytest test_app.py

      - name: Build Docker Image
        run: |
          docker build --progress=plain -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-docker-demo .

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Push Docker Image
        run: |
          docker tag flask-docker-demo gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-docker-demo
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-docker-demo

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy flask-app \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-docker-demo \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
