name: CI/CD Pipeline for Flask App

on:
  push:
    branches:
      - main # Trigger deployment when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run Python syntax check
      - name: Check Python Syntax
        run: |
          python -m py_compile $(find . -name "*.py")

      # Step 5: Run tests (optional, if you have pytest)
      - name: Run tests
        run: |
          pytest test_app.py

      # Step 6: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t flask-docker-demo .

      # Step 7: Deploy to Server (simulated here)
      - name: Deploy to Server
        run: |
          echo "Deploying to server..."
          echo "Pull the latest Docker image and start the container"

          # Simulating deployment (replace with actual deployment commands)
          echo "Running docker-compose up -d..."

          # In a real scenario, SSH into the server and execute Docker commands:
          # ssh user@your-server "cd /path/to/app && docker-compose pull && docker-compose up -d"

          # Since this is a simulation, we'll stop here:
          echo "Deployed!"
