name: CI/CD Pipeline for Flask App

on:
  push:
    branches:
      - main # Trigger deployment when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t flask-docker-demo .

      # Step 5: Deploy to Server (simulated here)
      - name: Deploy to Server
        run: |
          # In a real setup, you'd SSH to your server and run Docker commands to deploy the app
          echo "Deploying to server..."
          # Example: ssh user@server "docker pull flask-docker-demo && docker-compose up -d"
          # Here you might want to set up SSH keys for secure server login, but for now we'll just simulate
